CREATE TABLE [dbo].[Advertisements]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Ad1] NVARCHAR(MAX) NOT NULL, 
    [Ad2] NVARCHAR(MAX) NOT NULL, 
    [Ad3] NVARCHAR(MAX) NOT NULL, 
    [CreateDate] DATETIME2 NOT NULL
)
