CREATE TABLE [dbo].[Food]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FoodType] NVARCHAR(100) NOT NULL, 
    [FoodName] NVARCHAR(100) NOT NULL, 
    [Price] MONEY NOT NULL, 
    [TypeId] INT NOT NULL, 
    CONSTRAINT [FK_Food_ToFoodType] FOREIGN KEY (TypeId) REFERENCES FoodType(Id) 
)
